motion:
  -2 : BREAK
  -1 : STOP
#  0 : .
#  1 : .
#  2 : . 
#  3 : .
#  4 : .
#  5 : .  
  6 : Hello with hand
  7 : Hello with head
  8 : Looking around
  9 : .
  10 : .
  11 : .
  12 : .
  13 : .
  14 : .
  15 : .
  16 : .
  17 : .
  18 : .
  19 : .
  20 : .
  21 : .
  22 : .
  23 : .
  24 : .
  25 : .
  26 : .
  27 : .
  28 : .
  29 : .
  30 : .
  31 : .